
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

line_length:
 - 200
 - 300
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - ok
    - id
    - URL
    - GlobalAPIKey
    - lhs
    - rhs
    - a0_orange
    - i

force_cast: warning # implicitly. Give warning only for force casting

function_parameter_count:
  warning: 7
  error: 10
nesting:
    type_level: 3
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
vertical_whitespace:
  max_empty_lines: 1
cyclomatic_complexity:
  warning: 25
